# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GpaCalculator < Formula
  desc "A simple gpa calculator app that gets data off local files"
  homepage "https://github.com/kitesi/gpa-calculator"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kitesi/gpa-calculator/releases/download/v1.1.0/gpa-calculator_Darwin_x86_64.tar.gz"
      sha256 "fd124f20ff49a51b9d964d5053d9595c300e1d16eee688b6011dceef269ec34e"

      def install
        bin.install "gpa-calculator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kitesi/gpa-calculator/releases/download/v1.1.0/gpa-calculator_Darwin_arm64.tar.gz"
      sha256 "657651972b6490542f5d21fb4e5f726e029e163ab13e81fa3bb9c5f690b87a66"

      def install
        bin.install "gpa-calculator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kitesi/gpa-calculator/releases/download/v1.1.0/gpa-calculator_Linux_x86_64.tar.gz"
      sha256 "ab0c1bf26b7e243aeb3eb182a10e1b74c10ca01c131264c8ef563df0c0c83988"

      def install
        bin.install "gpa-calculator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitesi/gpa-calculator/releases/download/v1.1.0/gpa-calculator_Linux_arm64.tar.gz"
      sha256 "554fd8bbf8f18cd57d25cec301136810af5b685548681c3f861b522560fc28a7"

      def install
        bin.install "gpa-calculator"
      end
    end
  end
end
