# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GpaCalculator < Formula
  desc "A simple gpa calculator app that gets data off local files"
  homepage "https://github.com/kitesi/gpa-calculator"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kitesi/gpa-calculator/releases/download/v1.0.0/gpa-calculator_Darwin_arm64.tar.gz"
      sha256 "e3c0a82e86f9725afc4d491419a318d03694a8ff48dafeaf34fedfe31338d516"

      def install
        bin.install "gpa-calculator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kitesi/gpa-calculator/releases/download/v1.0.0/gpa-calculator_Darwin_x86_64.tar.gz"
      sha256 "f979311cbe280cc9f40ab979cac2927f2390aed88c81423b7731b47c6c33c777"

      def install
        bin.install "gpa-calculator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kitesi/gpa-calculator/releases/download/v1.0.0/gpa-calculator_Linux_x86_64.tar.gz"
      sha256 "aa8153584e6a97b30c46b9a82f19a9715291d8a9e3e8da8439661c8a6aaf141c"

      def install
        bin.install "gpa-calculator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitesi/gpa-calculator/releases/download/v1.0.0/gpa-calculator_Linux_arm64.tar.gz"
      sha256 "692b875c7e59a0aef9182485e1a9997fcbae46c3b9fb77a40925370c7b9475c3"

      def install
        bin.install "gpa-calculator"
      end
    end
  end
end
